### PR TITLE
Detect NAT type

### PR DESCRIPTION
**Pull request by xdyyll**
```
#include <stdio.h>                                                                                     
#include <string.h>                                                                                    
                                                                                                       
#include "nat.h"                                                                                       
                                                                                                       
#define DEFAULT_STUN_HOST "stun.ageneau.net"                                                           
#define DEFAULT_STUN_PORT 3478                                                                         
                                                                                                       
int main(void) {                                                                                       
    char *stun_host = DEFAULT_STUN_HOST;                                                               
    unsigned short stun_port = DEFAULT_STUN_PORT;                                                      
                                                                                                       
    addr_record_t mapped_addr;                                                                         
    juice_nat_type_t nat_type = juice_nat_detect(stun_host, stun_port, &mapped_addr);                  
                                                                                                       
    struct sockaddr_in *addr = (struct sockaddr_in *)&mapped_addr.addr;                                
    printf("Nat Type: %s\n", juice_nat_type_name(nat_type));                                           
    printf("Mapped Address: %s:%d\n", inet_ntoa(addr->sin_addr), ntohs(addr->sin_port));               
                                                                                                       
                                                                                                       
    return 0;                                                                                          
}
```
![nat-type-detect](https://user-images.githubusercontent.com/55201975/125829746-62416411-1765-4bb5-9cba-912f4dee58ef.png)

### CODE REVIEW

**Review by paullouisageneau — COMMENTED** [review]
Pretty cool, thanks! However, I'm puzzled. This relies on the server implementing RFC 5780, right? The support is uncommon as it requires two different IPv4 addresses on the server. My server `stun.ageneau.net` has only one, so how does this still work with it?

**Comment by xdyyll** [comment]
> Pretty cool, thanks! However, I'm puzzled. This relies on the server implementing RFC 5780, right? The support is uncommon as it requires two different IPv4 addresses on the server. My server `stun.ageneau.net` has only one, so how does this still work with it?

The server only needs to implement RFC 3489. If the server only has one IP, there will be no distinction between Symmetric and Port Restricted Cone.

https://datatracker.ietf.org/doc/html/rfc3489#page-19

**Comment by paullouisageneau** [comment]
Actually, RFC 3489 has been obsolete for a long time as it has been replaced by RFC 5389 which most servers implement (itself obsoleted by RFC 8489 last year). The NAT detection has been removed from the STUN standard and moved to an extension, RFC 5780.

https://datatracker.ietf.org/doc/html/rfc5389#section-12

```
There were three comprehension-required attributes, RESPONSE- ADDRESS, CHANGE-REQUEST, and CHANGED-ADDRESS, that have been removed from this specification. 

CHANGE-REQUEST and CHANGED-ADDRESS are now part of the NAT Behavior Discovery usage [BEHAVE-NAT], and the other is deprecated.
 ```

> If the server only has one IP, there will be no distinction between Symmetric and Port Restricted Cone.

Yes indeed, I guess it will be the case most of the time with this method.

**Comment by xdyyll** [comment]
😂 Our corp project still using RFC 3389 NAT Detecting，thx for your tips. I will try to implement RFC 8489 NAT Detecting later.

**Comment by paullouisageneau** [comment]
RFC 5780 is roughly equivalent to what was in RFC 3489 for NAT detection. I don't think there is a RFC 8489 specific extension though.

My concern is not really about RFC support here, as servers like coturn support RFC 5780, it's mostly that this way of detecting NAT behavior does not seem common to me (the two IPv4 address requirement on the server is kind of a deal-breaker nowadays). Moreover, it feels a bit legacy as the terminology completely changed in parallel to acknowledge NAT behavior can change over time (you have to remember the first version of STUN comes from a word pre-smartphone and ubiquitous carrier grade NATs on 3G/4G/5G).

You can see the new terminology described in [RFC 5128](https://www.ietf.org/rfc/rfc5128.txt), for instance:
```
[STUN] further classifies NAT implementations using the terms "Full
   Cone", "Restricted Cone", "Port Restricted Cone", and "Symmetric".
   Unfortunately, this terminology has been the source of much
   confusion.  For this reason, this document adapts terminology from
   [BEH-UDP] to distinguish between NAT implementations. 
   [...]
```

In practice, a lot of client implementations simply query two different STUN servers and look at the resulting server reflexive addresses. If they are different, the NAT uses endpoint-dependent mapping. Otherwise, it probably uses endpoint-independent mapping. NAT filtering is not really an issue here given ICE connections are simultaneously open from both sides. Of course, I'd welcome your input on this and I'm open to suggestions.

**Pull request closed without merging**
