### PR TITLE
If socket allocations fails try again without IPv6

### LINKED ISSUE #244: Attempting to `bind` a IPv6 socket fails with NordVPN Installed
This was reported upstream at https://github.com/obsproject/obs-studio/issues/10313

----

With NordVPN enabled I get the following error

```
udp.c:133: UDP socket binding failed, errno=10049 (this is a WSAEADDRNOTAVAIL)
```

However when I switch to `AF_INET` being the default (over `AF_INET6`) the tests pass.

@paullouisageneau I am going to open a PR that attempts again (with IPv4 forced). The `NordLynx` adapter claims to support IPv6 so I don't see any way we could detect this.

```
   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::723e:7ca:789d:a5aa%17
   IPv4 Address. . . . . . . . . . . : 10.5.0.2
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . : 0.0.0.0
```

### PR DESCRIPTION
**Pull request by Sean-Der**
Resolves #244

### CODE REVIEW

**Comment by paullouisageneau** [comment]
Thank you for looking into the issue. While I'm open to a mitigation, this looks like a bug with NordVPN split tunnelling on Windows, because binding on `IN6ADDR_ANY_INIT` should always work provided the host supports IPv6 (when no interface has a valid IPv6 address it should effectively listen on localhost for IPv6).

The way you implemented the retry logic introduces unwanted behaviors. For instance, when IPv4 only is available, if it fails at a some point it will retry with `prefer_ipv6 == false` which will behave exactly the same, probably leading to twice the same error. Also, in introduces a flag which I'd prefer to avoid.

IMHO you should do the reverse, socket binding should simply be moved in the address family loop with socket creation. This way, if a failure happens, it will retry with the next address family. I pushed a suggestion, does it work for you?

**Comment by Sean-Der** [comment]
@paullouisageneau Just tested and it works great! 

Any way you want to solve the problem I am in support of (you are the one who has to maintain the code)

**Comment by Sean-Der** [comment]
It is possible to get a new patch release of libdatachannel with this?

 No worries if not, but would be nice to go into next major OBS release with a clean slate :) this is the last issue I am aware of

**Comment by paullouisageneau** [comment]
@Sean-Der Sure, I'll include it in a new patch release shortly!

**Pull request merged**
